# https://hub.docker.com/_/postgres
version: "3.10"
services:
  postgres:
    image: postgres:10
    container_name: postgres
    hostname: localhost
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ${PWD}/scripts/init_table.sql:/docker-entrypoint-initdb.d/init_table.sql      
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - 5432:5432
    expose:
      - 5432