# https://hub.docker.com/_/postgres
version: "3.10"
services:
  db:
    container_name: db
    hostname: db
    image: postgres
    ports:
      - "54321:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}    
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data
      - ./data/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql